-- MySQL Script generated by MySQL Workbench
-- 10/31/14 19:42:28
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sicla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sicla` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `sicla` ;

-- -----------------------------------------------------
-- Table `sicla`.`usrTipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicla`.`usrTipes` (
  `idTipoUsr` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoUsr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sicla`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicla`.`user` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(16) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `password` VARCHAR(10) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idTipoUsr` INT NOT NULL DEFAULT 1,
  `nickname` VARCHAR(45) NULL,
  `imagen` VARCHAR(45) NULL DEFAULT 'imagenes/defaulUsr.jpg',
  PRIMARY KEY (`idUsuario`),
  INDEX `idTipoUsr_idx` (`idTipoUsr` ASC),
  CONSTRAINT `idTipoUsr`
    FOREIGN KEY (`idTipoUsr`)
    REFERENCES `sicla`.`usrTipes` (`idTipoUsr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `sicla`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicla`.`estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sicla`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicla`.`municipio` (
  `idMunicipio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idMunicipio`),
  INDEX `estado_idx` (`estado` ASC),
  CONSTRAINT `estado`
    FOREIGN KEY (`estado`)
    REFERENCES `sicla`.`estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sicla`.`Medio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicla`.`Medio` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(35) NOT NULL,
  `url` VARCHAR(75) NOT NULL,
  `imagen` VARCHAR(25) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sicla`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicla`.`Autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(65) NOT NULL,
  `genero` CHAR NOT NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sicla`.`colabora_en`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicla`.`colabora_en` (
  `idCE` INT NOT NULL AUTO_INCREMENT,
  `idAutor` INT NOT NULL,
  `idMedio` INT NOT NULL,
  INDEX `medio_idx` (`idMedio` ASC),
  PRIMARY KEY (`idCE`),
  UNIQUE INDEX `autor_fka_UNIQUE` (`idAutor` ASC, `idMedio` ASC),
  CONSTRAINT `medio_fkm`
    FOREIGN KEY (`idMedio`)
    REFERENCES `sicla`.`Medio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `autor_fka`
    FOREIGN KEY (`idAutor`)
    REFERENCES `sicla`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sicla`.`tipoNota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicla`.`tipoNota` (
  `idTN` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sicla`.`Nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicla`.`Nota` (
  `idNota` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `pagina` INT NOT NULL,
  `tipo` INT NOT NULL,
  `clasificacion` VARCHAR(45) NOT NULL,
  `sintesis` VARCHAR(254) NULL,
  `texto` MEDIUMTEXT NOT NULL,
  `numero` INT NOT NULL,
  `url` VARCHAR(45) NULL,
  `imagen` VARCHAR(40) NULL,
  `idMunicipio` INT NOT NULL,
  `idAdmin` INT NOT NULL,
  `idColaborador` INT NOT NULL,
  PRIMARY KEY (`idNota`),
  INDEX `municipio_idx` (`idMunicipio` ASC),
  INDEX `idAdmin_idx` (`idAdmin` ASC),
  INDEX `idColaborador_idx` (`idColaborador` ASC),
  INDEX `tipo_idx` (`tipo` ASC),
  CONSTRAINT `municipio_fk`
    FOREIGN KEY (`idMunicipio`)
    REFERENCES `sicla`.`municipio` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAdmin`
    FOREIGN KEY (`idAdmin`)
    REFERENCES `sicla`.`user` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idColaborador`
    FOREIGN KEY (`idColaborador`)
    REFERENCES `sicla`.`colabora_en` (`idCE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipo`
    FOREIGN KEY (`tipo`)
    REFERENCES `sicla`.`tipoNota` (`idTN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sicla`.`Protagonista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicla`.`Protagonista` (
  `idProtagonista` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(55) NOT NULL,
  `genero` CHAR NOT NULL,
  PRIMARY KEY (`idProtagonista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sicla`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicla`.`Area` (
  `idArea` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idArea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sicla`.`tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicla`.`tema` (
  `idTema` INT NOT NULL AUTO_INCREMENT,
  `idArea` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTema`),
  INDEX `idArea_idx` (`idArea` ASC),
  CONSTRAINT `idArea`
    FOREIGN KEY (`idArea`)
    REFERENCES `sicla`.`Area` (`idArea`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sicla`.`subtema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicla`.`subtema` (
  `idSubtema` INT NOT NULL AUTO_INCREMENT,
  `idTema` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSubtema`),
  INDEX `idTema_idx` (`idTema` ASC),
  CONSTRAINT `idTema`
    FOREIGN KEY (`idTema`)
    REFERENCES `sicla`.`tema` (`idTema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sicla`.`trata_de`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicla`.`trata_de` (
  `nota_fk3` INT NOT NULL,
  `subtema_fk` INT NOT NULL,
  INDEX `nota_idx` (`nota_fk3` ASC),
  INDEX `subtema_idx` (`subtema_fk` ASC),
  CONSTRAINT `nota_fk3`
    FOREIGN KEY (`nota_fk3`)
    REFERENCES `sicla`.`Nota` (`idNota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subtema_fk`
    FOREIGN KEY (`subtema_fk`)
    REFERENCES `sicla`.`subtema` (`idSubtema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sicla`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicla`.`Cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sicla`.`cargoProtagonista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicla`.`cargoProtagonista` (
  `idCP` INT NOT NULL AUTO_INCREMENT,
  `idCargo` INT NOT NULL,
  `idProtagonista` INT NOT NULL,
  UNIQUE INDEX `idProtagonista_UNIQUE` (`idProtagonista` ASC, `idCargo` ASC),
  PRIMARY KEY (`idCP`),
  CONSTRAINT `idCargo`
    FOREIGN KEY (`idCargo`)
    REFERENCES `sicla`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProtagonsita`
    FOREIGN KEY (`idProtagonista`)
    REFERENCES `sicla`.`Protagonista` (`idProtagonista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sicla`.`notaProtagonista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicla`.`notaProtagonista` (
  `idNota` INT NOT NULL,
  `idCP` INT NOT NULL,
  `tipo` INT NOT NULL,
  INDEX `idNota_idx` (`idNota` ASC),
  INDEX `idCP_idx` (`idCP` ASC),
  PRIMARY KEY (`idNota`, `idCP`),
  CONSTRAINT `idNota`
    FOREIGN KEY (`idNota`)
    REFERENCES `sicla`.`Nota` (`idNota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCP`
    FOREIGN KEY (`idCP`)
    REFERENCES `sicla`.`cargoProtagonista` (`idCP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
